/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcudaui;

/**
 *
 * @author Ayaz-ul-Hassan
 */
public class RTCUDAUI extends javax.swing.JFrame {

    /**
     * Creates new form RTCUDAUI
     */
    public RTCUDAUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMatrixDim = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnLoadFile = new javax.swing.JButton();
        btnAddKernel = new javax.swing.JButton();
        btnAddMain = new javax.swing.JButton();
        pnlConfigurations = new javax.swing.JPanel();
        chkLoopCollapsing = new javax.swing.JCheckBox();
        chkBlockSkew = new javax.swing.JCheckBox();
        chkPrefetching = new javax.swing.JCheckBox();
        rb1DMatrix = new javax.swing.JRadioButton();
        rb2DMatrix = new javax.swing.JRadioButton();
        txtPrefetchedArrays = new javax.swing.JTextField();
        txtNonPrefetchedArrays = new javax.swing.JTextField();
        cbDataType = new javax.swing.JComboBox<>();
        lblDataType = new javax.swing.JLabel();
        lblKernelName = new javax.swing.JLabel();
        txtKernelName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRowDimension = new javax.swing.JTextField();
        slMaxBlockSize = new javax.swing.JSlider();
        lblMaxBlockSize = new javax.swing.JLabel();
        lblMaxMergeLevel = new javax.swing.JLabel();
        slMaxMergeLevel = new javax.swing.JSlider();
        lblMaxSkewLevel = new javax.swing.JLabel();
        slMaxSkewLevel = new javax.swing.JSlider();
        lblMinBlockSize = new javax.swing.JLabel();
        slMinBlockSize = new javax.swing.JSlider();
        lblMinMergeLevel = new javax.swing.JLabel();
        slMinMergeLevel = new javax.swing.JSlider();
        lblMinSkewLevel = new javax.swing.JLabel();
        slMinSkewLevel = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lstFiles = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnRemoveFile = new javax.swing.JButton();
        pbRestructuringStatus = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RTCUDA: A Software Tool for CUDA Restructuring");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitle.setText("Code Area");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnLoadFile.setText("Load File");

        btnAddKernel.setText("Add Kernel");

        btnAddMain.setText("Add Main");

        pnlConfigurations.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kernel Configurations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlConfigurations.setName(""); // NOI18N

        chkLoopCollapsing.setText("Loop Collapsing");

        chkBlockSkew.setText("Block Skew");

        chkPrefetching.setText("Prefetching");

        bgMatrixDim.add(rb1DMatrix);
        rb1DMatrix.setSelected(true);
        rb1DMatrix.setText("1D Matrix");

        bgMatrixDim.add(rb2DMatrix);
        rb2DMatrix.setText("2D Matrix");

        txtPrefetchedArrays.setToolTipText("Comma Separated List of Array Variables to be Prefetched");

        txtNonPrefetchedArrays.setToolTipText("Comma Separated List of Array Variables not to be Prefetched");

        cbDataType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "float", "double" }));
        cbDataType.setSelectedItem("float");

        lblDataType.setText("Data Type");

        lblKernelName.setText("Kernel Name");

        jLabel1.setText("Row Dim");

        slMaxBlockSize.setMajorTickSpacing(512);
        slMaxBlockSize.setMaximum(2048);
        slMaxBlockSize.setPaintLabels(true);
        slMaxBlockSize.setPaintTicks(true);
        slMaxBlockSize.setSnapToTicks(true);
        slMaxBlockSize.setValue(0);

        lblMaxBlockSize.setText("Maximum Block Size:");

        lblMaxMergeLevel.setText("Maximum Merge Level:");

        slMaxMergeLevel.setMajorTickSpacing(4);
        slMaxMergeLevel.setMaximum(32);
        slMaxMergeLevel.setMinorTickSpacing(2);
        slMaxMergeLevel.setPaintLabels(true);
        slMaxMergeLevel.setPaintTicks(true);
        slMaxMergeLevel.setSnapToTicks(true);
        slMaxMergeLevel.setValue(0);

        lblMaxSkewLevel.setText("Maximum Skew Level:");

        slMaxSkewLevel.setMajorTickSpacing(4);
        slMaxSkewLevel.setMaximum(32);
        slMaxSkewLevel.setMinorTickSpacing(2);
        slMaxSkewLevel.setPaintLabels(true);
        slMaxSkewLevel.setPaintTicks(true);
        slMaxSkewLevel.setSnapToTicks(true);
        slMaxSkewLevel.setValue(0);

        lblMinBlockSize.setText("Minimum Block Size:");

        slMinBlockSize.setMajorTickSpacing(256);
        slMinBlockSize.setMaximum(1024);
        slMinBlockSize.setPaintLabels(true);
        slMinBlockSize.setPaintTicks(true);
        slMinBlockSize.setSnapToTicks(true);
        slMinBlockSize.setValue(0);

        lblMinMergeLevel.setText("Minimum Merge Level:");

        slMinMergeLevel.setMajorTickSpacing(4);
        slMinMergeLevel.setMaximum(16);
        slMinMergeLevel.setMinorTickSpacing(2);
        slMinMergeLevel.setPaintLabels(true);
        slMinMergeLevel.setPaintTicks(true);
        slMinMergeLevel.setSnapToTicks(true);
        slMinMergeLevel.setValue(0);

        lblMinSkewLevel.setText("Minimum Skew Level:");

        slMinSkewLevel.setMajorTickSpacing(4);
        slMinSkewLevel.setMaximum(16);
        slMinSkewLevel.setMinorTickSpacing(2);
        slMinSkewLevel.setPaintLabels(true);
        slMinSkewLevel.setPaintTicks(true);
        slMinSkewLevel.setSnapToTicks(true);
        slMinSkewLevel.setValue(0);

        jLabel2.setText("Prefetched Arrays");

        jLabel3.setText("Non Prefetched Arrays");

        javax.swing.GroupLayout pnlConfigurationsLayout = new javax.swing.GroupLayout(pnlConfigurations);
        pnlConfigurations.setLayout(pnlConfigurationsLayout);
        pnlConfigurationsLayout.setHorizontalGroup(
            pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                .addComponent(rb1DMatrix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb2DMatrix)
                .addContainerGap())
            .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                        .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                                .addComponent(chkLoopCollapsing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkBlockSkew)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfigurationsLayout.createSequentialGroup()
                                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkPrefetching, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNonPrefetchedArrays, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtPrefetchedArrays, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(2, 2, 2)
                        .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                                .addComponent(lblDataType)
                                .addGap(18, 18, 18)
                                .addComponent(lblKernelName))
                            .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                                .addComponent(cbDataType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKernelName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfigurationsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRowDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                        .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlConfigurationsLayout.createSequentialGroup()
                                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblMaxBlockSize))
                                    .addComponent(slMaxBlockSize, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slMaxMergeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaxMergeLevel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlConfigurationsLayout.createSequentialGroup()
                                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slMinBlockSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblMinBlockSize)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMinMergeLevel)
                                    .addComponent(slMinMergeLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaxSkewLevel)
                            .addComponent(slMaxSkewLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slMinSkewLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMinSkewLevel))))
                .addGap(13, 13, 13))
        );
        pnlConfigurationsLayout.setVerticalGroup(
            pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigurationsLayout.createSequentialGroup()
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb2DMatrix)
                    .addComponent(rb1DMatrix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLoopCollapsing)
                    .addComponent(chkBlockSkew)
                    .addComponent(chkPrefetching)
                    .addComponent(lblDataType)
                    .addComponent(lblKernelName)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrefetchedArrays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDataType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKernelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRowDimension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNonPrefetchedArrays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxBlockSize)
                    .addComponent(lblMaxMergeLevel)
                    .addComponent(lblMaxSkewLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slMaxBlockSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slMaxMergeLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slMaxSkewLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinBlockSize)
                    .addComponent(lblMinMergeLevel)
                    .addComponent(lblMinSkewLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slMinBlockSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slMinMergeLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slMinSkewLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );

        lstFiles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Files", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lstFiles.setViewportView(jList1);

        btnRemoveFile.setText("Remove");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnLoadFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAddKernel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAddMain))
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lstFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRemoveFile)
                                .addGap(45, 45, 45)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlConfigurations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbRestructuringStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlConfigurations, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbRestructuringStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lstFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoveFile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(btnLoadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddKernel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RTCUDAUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RTCUDAUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RTCUDAUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RTCUDAUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RTCUDAUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMatrixDim;
    private javax.swing.JButton btnAddKernel;
    private javax.swing.JButton btnAddMain;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnRemoveFile;
    private javax.swing.JComboBox<String> cbDataType;
    private javax.swing.JCheckBox chkBlockSkew;
    private javax.swing.JCheckBox chkLoopCollapsing;
    private javax.swing.JCheckBox chkPrefetching;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblDataType;
    private javax.swing.JLabel lblKernelName;
    private javax.swing.JLabel lblMaxBlockSize;
    private javax.swing.JLabel lblMaxMergeLevel;
    private javax.swing.JLabel lblMaxSkewLevel;
    private javax.swing.JLabel lblMinBlockSize;
    private javax.swing.JLabel lblMinMergeLevel;
    private javax.swing.JLabel lblMinSkewLevel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane lstFiles;
    private javax.swing.JProgressBar pbRestructuringStatus;
    private javax.swing.JPanel pnlConfigurations;
    private javax.swing.JRadioButton rb1DMatrix;
    private javax.swing.JRadioButton rb2DMatrix;
    private javax.swing.JSlider slMaxBlockSize;
    private javax.swing.JSlider slMaxMergeLevel;
    private javax.swing.JSlider slMaxSkewLevel;
    private javax.swing.JSlider slMinBlockSize;
    private javax.swing.JSlider slMinMergeLevel;
    private javax.swing.JSlider slMinSkewLevel;
    private javax.swing.JTextField txtKernelName;
    private javax.swing.JTextField txtNonPrefetchedArrays;
    private javax.swing.JTextField txtPrefetchedArrays;
    private javax.swing.JTextField txtRowDimension;
    // End of variables declaration//GEN-END:variables
}
